
---
# Best practice is to group servers and network devices by their
# - What (application, stack or microservice)
# - Where (datacenter or region)
# - When (development stage)
# Group names are case sensitive.
# Define the hostnames in /etc/hosts on the ansible control host

# Single Board Computers
sbc:
  hosts:
    nanopim4v2:
    odroidc2:

# Virtual Private Servers
vps:
  hosts:
    conta-de1:
    conta-de2:
    conta-us1:

all:
  children:
    vps:
    sbc:

# Kubernetes Groups
k3s_masters:
  hosts:
    conta-de1:

k3s_nodes:
  hosts:
    conta-us1:

kubernetes:
  children:
    k3s_masters:
    k3s_nodes: