
---
# Best practice is to group servers and network devices by their 
# What (application, stack or microservice), Where (datacenter or region), and When (development stage)
# Group names are case sensitive.
# Define the hostnames in /etc/hosts on the ansible control host

k3s_masters:
  hosts:
    conta-de1:
    conta-us1:

k3s_nodes:
  hosts:
    conta-de2:
    nanopim4v2:

kubernetes:
  children:
    k3s_masters:
    k3s_nodes:

sbc:
  hosts:
    nanopim4v2:
    odroidc2:

all:
  children:
    kubernetes:
    sbc:

