#######################
# Initial Server Setup
#######################
---
- hosts: kubernetes
  become: true
  vars_files:
    - vars/default.yml
  vars:
    master_ip1: "{{hostvars['conta-de1']['ansible_default_ipv4']['address']}}"
    master_ip2: "{{hostvars['conta-us1']['ansible_default_ipv4']['address']}}"
    docker_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64'}}"
  tasks:      
    - name: Install Prerequisites
      apt:
        name: aptitude
        update_cache: yes
        state: latest
        force_apt_get: yes

    - name: Install sudo
      apt:
        name: sudo

    - name: Check if user exists
      shell: /usr/bin/getent passwd | awk -F":" '{print $1}'
      register: etc_groups

    - name: Creating user "{{ create_user }}" with admin access
      user:
        name: "{{ create_user }}"
        password: "{{ upasswd | password_hash('sha512') }}"
        state: present
        groups: sudo
        append: true
        create_home: true
        shell: /bin/bash
      when: '"{{create_user}}" in etc_groups.stdout_lines'

    - name: Allow sudo to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^%sudo"
        line: "%sudo ALL=(ALL) NOPASSWD: ALL"
        validate: "/usr/sbin/visudo -cf %s"

    - name: Setup authorized key for remote user
      authorized_key:
        user: "{{ create_user }}"
        state: present
        key: "{{ copy_local_key }}"
      when: '"{{create_user}}" in etc_groups.stdout_lines'
    
      # SSH setup
    - name: Disable password authentication for root login in SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin prohibit-password"
      register: sshconfig

    - name: Disable password login
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "#?.*PasswordAuthentication.*"
        line: "PasswordAuthentication no"
      register: sshconfig

    - name: Restart SSH
      service:
        name: ssh
        state: restarted
      when: sshconfig.changed

    # Install Packages
    - name: Install required system packages
      apt:
        name: "{{ sys_packages }}"
        state: latest
    - name: Check for docker binary
      stat:
        path: /usr/bin/docker
      register: dockerbin

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/{{ansible_os_family | lower}}/gpg
        state: present
      when: not dockerbin.stat.exists
    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch={{docker_arch}}] https://download.docker.com/linux/{{ansible_os_family| lower}} {{ansible_distribution_release | lower}} stable"
        state: present
      when: not dockerbin.stat.exists
    - name: Install Docker
      apt:
        name: "{{ docker_packages }}"
        state: latest
      when: not dockerbin.stat.exists
    
    - name: Setup UFW - Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH
    - name: Setup UFW - Allow 443/tcp connections
      ufw:
        rule: allow
        port: "443"
        proto: tcp
        comment: For HTTPS and k3s (SSL/TLS)
    - name: Setup UFW - Allow 6443/tcp connections
      ufw:
        rule: allow
        port: "6443"
        proto: tcp
        comment: For k3s
    - name: Setup UFW - Allow  8472/udp connections
      ufw:
        rule: allow
        port: "8472"
        proto: udp
        comment: For k3s
    - name: UFW - Deny all other incoming traffic by default
      ufw:
        state: enabled
        policy: deny
        direction: incoming
      when: "'nanopim4v2' not in group_names"
