---
create_user: "{{newuser}}"
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
sys_packages: [ 'curl', 'vim', 'git', 'ufw', 'nginx', 'fail2ban', 'rsync', 'jq', 'htop']
docker_sys_packages: [ 'apt-transport-https', 'ca-certificates', 'gnupg', 'lsb-release']
docker_packages: [ 'docker-ce', 'docker-ce-cli', 'containerd.io']
kubernetes_packages: ['mariadb-server']