---
create_user: "{{newuser}}"
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
sys_packages: [ 'curl', 'vim', 'git', 'ufw', 'apt-transport-https', 'ca-certificates', 'gnupg', 'mariadb-server']
docker_packages: [ 'docker-ce', 'docker-ce-cli', 'containerd.io']